### ISSUE TITLE
Tutorial-Screen

### ISSUE THREAD

**Issue by felberto** [felberto/nonogramm#3]

**Comment by Meli-01** [comment]
Kannst du die Liste noch linksbündig darstellen?

![image](https://user-images.githubusercontent.com/47660505/64941184-36d98680-d866-11e9-862d-0d02c4af8913.png)

**Comment by felberto** [comment]
> Kannst du die Liste noch linksbündig darstellen?
> 
> ![image](https://user-images.githubusercontent.com/47660505/64941184-36d98680-d866-11e9-862d-0d02c4af8913.png)

kann ich machen
